services:
  nest-app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    environment:
      DB_HOST_SQLSERVER: 190.231.99.215
      DB_PORT_SQLSERVER: 1435
      DB_USERNAME_SQLSERVER: worky
      DB_PASSWORD_SQLSERVER: retail109
      DB_DATABASE_SQLSERVER: AbrilSRL
      DB_HOST_POSTGRES: postgres
      DB_PORT_POSTGRES: 5432
      DB_USERNAME_POSTGRES: postgres
      DB_PASSWORD_POSTGRES: postgres
      DB_DATABASE_POSTGRES: MyPostgresDB
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MyPostgresDB
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

